export const ADMIN_STATUS_COLORS: Record<string, string> = {
  open: 'var(--primary, #0F766E)',
  accepted: 'var(--secondary, #2563EB)',
  assigned: 'var(--secondary, #2563EB)',
  'in progress': 'var(--warning, #D97706)',
  in_progress: 'var(--warning, #D97706)',
  submitted: 'var(--purple, #9333EA)',
  completed: 'var(--success, #16A34A)',
  cancelled: 'var(--outline, #64748B)',
  takedown: 'var(--error, #DC2626)',
};

export const ADMIN_PIE_PALETTE = [
  'var(--primary, #0F766E)',
  'var(--secondary, #2563EB)',
  'var(--warning, #D97706)',
  'var(--success, #16A34A)',
  'var(--purple, #9333EA)',
  'var(--error, #DC2626)',
  'var(--outline, #64748B)',
];

export const CATEGORY_ICON_OPTIONS_RAW = [
  { value: 'Camera', label: 'Camera (Fotografi)' },
  { value: 'Laptop', label: 'Laptop (Data Entry)' },
  { value: 'Palette', label: 'Palette (Desain)' },
  { value: 'FileText', label: 'FileText (Penulisan)' },
  { value: 'Box', label: 'Box (Jaga Booth)' },
  { value: 'Truck', label: 'Truck (Kurir)' },
  { value: 'Wrench', label: 'Wrench (Teknis IT)' },
  { value: 'Smartphone', label: 'Smartphone (Sosmed)' },
  { value: 'GraduationCap', label: 'GraduationCap (Tutoring)' },
  { value: 'Folder', label: 'Folder (Umum)' },
  { value: 'Sparkles', label: 'Sparkles (Kreatif / Spesial)' },
  { value: 'Code', label: 'Code (Programming)' },
  { value: 'PenTool', label: 'PenTool (Ilustrasi)' },
  { value: 'Megaphone', label: 'Megaphone (Marketing)' },
  { value: 'Music', label: 'Music (Audio)' },
  { value: 'Video', label: 'Video (Editing/Produksi)' },
  { value: 'Languages', label: 'Languages (Bahasa)' },
  { value: 'Briefcase', label: 'Briefcase (Bisnis)' },
  { value: 'Calculator', label: 'Calculator (Akuntansi)' },
  { value: 'ChefHat', label: 'ChefHat (Kuliner)' },
  { value: 'HeartPulse', label: 'HeartPulse (Kesehatan)' },
  { value: 'Scissors', label: 'Scissors (Salon/Kecantikan)' },
  { value: 'Brush', label: 'Brush (Seni Lukis)' },
  { value: 'Hammer', label: 'Hammer (Tukang/Bangunan)' },
  { value: 'Activity', label: 'Activity (Fitness/Olahraga)' },
  { value: 'Cpu', label: 'Cpu (Hardware/Server)' },
  { value: 'Globe', label: 'Globe (Web/Internet)' },
  { value: 'Users', label: 'Users (SDM/Manajemen)' },
  { value: 'Database', label: 'Database (Data Science)' },
  { value: 'ShoppingCart', label: 'ShoppingCart (E-Commerce)' },
  { value: 'TrendingUp', label: 'TrendingUp (Sales/Bisnis)' },
  { value: 'Car', label: 'Car (Otomotif/Sopir)' },
  { value: 'Shield', label: 'Shield (Keamanan/Security)' },
  { value: 'Mic', label: 'Mic (Voiceover/MC)' },
  { value: 'Gamepad', label: 'Gamepad (Gaming)' },
];
